### ISSUE TITLE
'Calculate Centiles and Create Chart' button 

### ISSUE THREAD

**Issue by magdaumerska** [rcpch/digital-growth-charts-react-client#42] opened 2021-02-05 09:58 UTC
When I enter my test measurement on https://growth.rcpch.ac.uk/ and hit 'Calculate Centiles and Create Chart' button - it doesn't plot data on the chart and the calculation is missing. Occasionally, when I hit the button, it gives blank page.

**Comment by pacharanero** [comment] 2021-02-05 15:12
Yes we had noticed this weird issue. `alpha` is apparently running the exact same code as `unstable` at the moment, but for some reason we are still getting the javascript error

Uncaught (in promise) TypeError: Cannot read property 'length' of undefined

When doing calculations
@eatyourpeas

**Comment by eatyourpeas** [comment] 2021-02-05 15:22
yes I think this is a latency issue as the same code works on unstable and locally. The length refers to the array of measurements passed in from the client to the chart package. It appears the chart package is loading before the prop arrives and therefore breaking. Because it was working locally, I pushed to unstable and merged with alpha. I am sorry. I will look at it over the weekend.

**Comment by pacharanero** [comment] 2021-02-05 15:28
OK. I'm off nights now and might be able to look at this over weekend with you

**Comment by pacharanero** [comment] 2021-02-06 13:29
Thanks @magdaumerska for reporting, we've worked out what the issue was now. The growth.rcpch.ac.uk site uses the `alpha` code branch of the React client. And it gets its data from the `alpha` branch of the server. Over the past month we had made improvements to the Client and the Server but we hadn't pushed those changes to the `alpha` server. That's all it was. Basically an oversight. I've pulled the more recent code into the `alpha` server and I can confirm it's fixed now.

**Closed as completed by pacharanero** 2021-02-06 13:29 UTC
Labels: bug, mvp
